INSERT INTO travel_interests (
    interest_id,
    interest_type,
    interest_attributes,
    season_name,
    travel_time_frame
) VALUES
    (1, 'Wellness', 'masszázs szalonok, szaunavilág, relaxáció, spa-hotelek', 'Nyár', 'Június és Augusztus között'),
    (2, 'Wellness', 'masszázs szalonok, szaunavilág, relaxáció, spa-hotelek', 'Ősz', 'Szeptember és November között'),
    (3, 'Wellness', 'masszázs szalonok, szaunavilág, relaxáció, spa-hotelek', 'Tél', 'December és Február között'),
    (4, 'Wellness', 'masszázs szalonok, szaunavilág, relaxáció, spa-hotelek', 'Tavasz', 'Március és Május között'),
    (5, 'Gastronomia', 'borászatok, termelői piacok, fine dining, helyi specialitások', 'Nyár', 'Június és Augusztus között'),
    (6, 'Gastronomia', 'borászatok, termelői piacok, fine dining, helyi specialitások', 'Ősz', 'Szeptember és November között'),
    (7, 'Gastronomia', 'borászatok, termelői piacok, fine dining, helyi specialitások', 'Tél', 'December és Február között'),
    (8, 'Gastronomia', 'borászatok, termelői piacok, fine dining, helyi specialitások', 'Tavasz', 'Március és Május között'),
    (9, 'Aktív turizmus', 'kerékpározás, vitorlázás, túraútvonalak, vízi sportok', 'Nyár', 'Június és Augusztus között'),
    (10, 'Aktív turizmus', 'kerékpározás, vitorlázás, túraútvonalak, vízi sportok', 'Ősz', 'Szeptember és November között'),
    (11, 'Aktív turizmus', 'kerékpározás, vitorlázás, túraútvonalak, vízi sportok', 'Tél', 'December és Február között'),
    (12, 'Aktív turizmus', 'kerékpározás, vitorlázás, túraútvonalak, vízi sportok', 'Tavasz', 'Március és Május között'),
    (13, 'Egészségturizmus', 'termálvíz, orvosi rehabilitáció, gyógykúrák, gyógytorna', 'Nyár', 'Június és Augusztus között'),
    (14, 'Egészségturizmus', 'termálvíz, orvosi rehabilitáció, gyógykúrák, gyógytorna', 'Ősz', 'Szeptember és November között'),
    (15, 'Egészségturizmus', 'termálvíz, orvosi rehabilitáció, gyógykúrák, gyógytornák', 'Tél', 'December és Február között'),
    (16, 'Egészségturizmus', 'termálvíz, orvosi rehabilitáció, gyógykúrák, gyógytornák', 'Tavasz', 'Március és Május között'),
    (17, 'Kultúra és események', 'várak, fesztiválok, múzeumok, történelmi emlékhelyek, templomok', 'Nyár', 'Június és Augusztus között'),
    (18, 'Kultúra és események', 'várak, fesztiválok, múzeumok, történelmi emlékhelyek, templomok', 'Ősz', 'Szeptember és November között'),
    (19, 'Kultúra és események', 'várak, fesztiválok, múzeumok, történelmi emlékhelyek, templomok', 'Tél', 'December és Február között'),
    (20, 'Kultúra és események', 'várak, fesztiválok, múzeumok, történelmi emlékhelyek, templomok', 'Tavasz', 'Március és Május között'),
    (21, 'Természet- és ökoturizmus', 'nemzeti parkok, tanösvények, madármegfigyelés, érintetlen táj, sátrazás', 'Nyár', 'Június és Augusztus között'),
    (22, 'Természet- és ökoturizmus', 'nemzeti parkok, tanösvények, madármegfigyelés, érintetlen táj, sátrazás', 'Ősz', 'Szeptember és November között'),
    (23, 'Természet- és ökoturizmus', 'nemzeti parkok, tanösvények, madármegfigyelés, érintetlen táj, sátrazás', 'Tél', 'December és Február között'),
    (24, 'Természet- és ökoturizmus', 'nemzeti parkok, tanösvények, madármegfigyelés, érintetlen táj, sátrazás', 'Tavasz', 'Március és Május között'),
    (25, 'Agroturizmus', 'tanyasi szálláshelyek, szüret, kézműves műhelyek, vidéki életforma', 'Nyár', 'Június és Augusztus között'),
    (26, 'Agroturizmus', 'tanyasi szálláshelyek, szüret, kézműves műhelyek, vidéki életforma', 'Ősz', 'Szeptember és November között'),
    (27, 'Agroturizmus', 'tanyasi szálláshelyek, szüret, kézműves műhelyek, vidéki életforma', 'Tél', 'December és Február között'),
    (28, 'Agroturizmus', 'tanyasi szálláshelyek, szüret, kézműves műhelyek, vidéki életforma', 'Tavasz', 'Március és Május között')
ON CONFLICT (interest_id) DO UPDATE SET
    interest_type = EXCLUDED.interest_type,
    interest_attributes = EXCLUDED.interest_attributes,
    season_name = EXCLUDED.season_name,
    travel_time_frame = EXCLUDED.travel_time_frame;
